//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey
    {
        public int SurveyId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string SurveyDesc { get; set; }
        public Nullable<int> OrgId { get; set; }
    
        public virtual Organization Organization { get; set; }
    }
}
